## Course details

**Class time/location**: Tuesdays 9:10a.m. – 12:00p.m., 410 Milbank               
**Instructor**: Annie Vu, Ph.D. (she/her/hers)                                   
**Email**: [avu@barnard.edu](mailto:avu@barnard.edu)                          
**Office hours**: M/W 1:00–2:00p.m.; T 1:00–3:00p.m.                               
**Prerequisites**: PSYC BC1001 Introduction to Psychology; PSYC BC1101 Statistics; PSYC BC1020 Research Methods.

**Co-requisite**: PSYC BC2125 Personality Psychology.                

::: {.callout-tip appearance="simple"}
Please include "PSYC 2124" in the subject line of any email. Office hours can be
in person or on Zoom by appointment — request via email or in person.
:::

## Course overview

This lab will usually be taken concurrently with the BC2125 Personality
lecture. It expands upon some of the theoretical, methodological, and analytic
issues introduced there, and gives you the opportunity to explore topics from
within and beyond those covered in the lectures in greater depth, through
hands-on experience with research design and data analysis.

The semester is broken into three projects, each illustrating a common
methodological and analytic approach in personality psychology. Projects are
undertaken in small groups; group members collaborate on design and analysis.
Each project culminates in an in-class group presentation and the submission of
a brief individual write-up.

### Course goals

Through these projects, you will gain experience in:

- Formulating psychological research questions relating to personality,
- Analyzing and visualizing data, and
- Interpreting and communicating your findings.

### Course format

This is a lab course that meets once per week. Labs are substantially more
interactive and discussion-based than the traditional lecture format, and
depend on everyone's active participation in class discussions and activities
as well as group work focused on the projects. Your active participation across
the semester will therefore contribute a substantial portion of your grade.

### Workload

As a general rule for the amount of time students should expect to commit to
classes, the college suggests three hours per week in or outside of class per
credit. Since this class is worth 2.5 credits, that corresponds to 7.5 hours
per week, split between time in the classroom and time spent completing the
associated assignments.

## Course requirements and assignments

### Attendance and participation (10%)

Active attendance and participation in class discussions and activities are
expected. Normally it is departmental policy to remove students who miss more
than two lab sessions from the course; however, given ongoing revisions to
college-wide health-related policies, exceptions may be made.

If you are feeling unwell, you should not come to class, and should notify me
of nonattendance before class if possible. When you are attending, please
arrive on time — frequent lateness will impact your participation grade.

If you have questions, thoughts, or ideas you want to share, feel free to do so
at any time. Keep within the bounds of polite conversation, obviously. Don't
interrupt or talk over other people, but do feel free to respond to others
without having to raise your hand or wait to be called on. Everyone gets the
most out of this lab when discussion develops organically and everyone feels
free to be part of the conversation when they have something to add.

Being part of the in-person discussion is one obvious way to participate, but
it isn't the only way. Different people have different styles of participation,
and the lab is designed to accommodate and encourage different approaches. Your
level of engagement with your project partners as you work through your
projects is also an important form of participation. You can also participate
by coming to office hours.

At a minimum — that is, for a passing grade — I'll be looking for some form of
participation, loosely defined, from you every week. Higher participation
grades are earned through regular, enthusiastic, productive participation.
Quality matters more than quantity.

### Presentations (30%)

Each project culminates in an in-class group presentation, given on the dates
listed in the schedule below. All group members are expected to contribute
equally to the preparation and delivery, and all group members receive the same
group score, except in exceptional circumstances when it is clear that
contributions were not equal.

If a group member is unable to present in person on the day of the presentation
due to unforeseen circumstances, please notify Prof. Vu. The presentation will
be given by the remaining group members, and the absent member may be assigned
the group score, assuming equal contributions to the preparation.

### Reports (60%)

Each project also requires a brief individual write-up. Written project reports
are due one week following the in-class presentation, which is before the next
week's lab session — see the schedule below for dates.

While you will collaborate with group members on the design, analysis, and
presentation of research projects, you may **not** collaborate on the written
report. Each group member must write their own individual report.

### Grading policy

|                                                | Weight |
|------------------------------------------------|-------:|
| Participation (over the course of the semester) | 10% |
| Presentations                                   | 30% |
| Reports                                         | 60% |
| **Total**                                       | **100%** |

### Grade assignment

Final grades are determined according to the following boundaries:

| Grade | Range | Grade | Range |
|-------|-------|-------|-------|
| A+ | 97–100% | C+ | 77–79.9% |
| A  | 93–96.9% | C | 73–76.9% |
| A- | 90–92.9% | C- | 70–72.9% |
| B+ | 87–89.9% | D | 60–69.9% |
| B  | 83–86.9% | F | below 60% |
| B- | 80–82.9% | | |

## Course schedule

| Date | Session focus | Due |
|------|---------------|-----|
| Tue, 9/8 | Course overview | |
| ***Project 1: $t$-test***|  | |
| Tue, 9/15 | Project planning | |
| Tue, 9/22 | Data preparation | |
| Tue, 9/29 | Analysis | |
| Tue, 10/6 | **Project 1 presentations** (in class) | |
| ***Project 2: Correlation*** | | |
| Tue, 10/13 | Project planning | **Project 1 report due** |
| Tue, 10/20 | Data preparation | |
| Tue, 10/27 | Analysis | |
| Tue, 11/3 | *No class — Election Day, College closed* | |
| Tue, 11/10 | **Project 2 presentations** (in class) | |
|***Project 3: Regression*** |  | |
| Tue, 11/17 | Project planning | **Project 2 report due** |
| Tue, 11/24 | Data preparation | |
| Tue, 12/1 | Analysis | |
| Tue, 12/8 | **Project 3 presentations** (in class) | |
| Tue, 12/15 | *No class — reading period* | **Project 3 report due** |


## Course policies

### Academic integrity

Cheating, plagiarism, and other violations of the Student Code of Conduct,
Honor Code, and Conduct Process will result in academic consequences. As a
Barnard student, you are responsible for reviewing the
[Student Code of Conduct, Honor Code, and Conduct Process](https://barnard.edu/honor-code).
Violations will be reported to the Honor Board.

You may collaborate with group members on the design, analysis, and
presentation of research projects, but you may **not** collaborate on the
written report.

### Accessibility

I want this course to provide equitable opportunities for learning. If you have
a letter from the
[Center for Accessibility Resources & Disability Services (CARDS)](https://barnard.edu/disability-services)
or have other needs that I can accommodate, please speak with me by the end of
the second week of the term to ensure I am able to respond in a timely manner.
Should your needs change during the semester, I will be happy to work with you
and CARDS to adapt accordingly. All discussions will remain confidential,
although CARDS may be consulted to discuss appropriate implementation of
accommodations.

### Academic accommodations and general wellness

It is always important to recognize the different pressures, burdens, and
stressors you may be facing, whether personal, emotional, physical, financial,
mental, or academic. The faculty and administration recognize this and are
prepared to provide assistance to students in need.

I encourage you to seek advice from your advisor, your Dean, CARDS, or
[Barnard Health & Wellness](https://barnard.edu/health-wellness) as needed.
Please let me know of any issues you wish to share with me that you feel are
impacting your ability to complete the course to the best of your ability.
Though it isn't always easy, it is better to proactively seek help than to let
problems build up.

### Late submission policy {#sec-late-policy}

Written project reports are due one week following the in-class presentation. A
grade penalty of 5 points will be applied for each day (or part thereof) that
an assignment is late, up to a maximum of 6 days. Work not submitted before the
next lab will receive a score of zero.

For example, if your work is A+ quality but is submitted a day and a half late,
you will only receive a B+.

This policy is intended to incentivize timely submission while easing the
stress of genuine emergencies. When things come up that prevent timely
submission you can prioritize accordingly, knowing that a small penalty on one
assignment for this lab will not tank your final grade.

### Use of electronics

Electronic devices are permitted for notetaking and class-related activities
only. Non-class-related use of electronics, such as browsing social media or
gaming, is prohibited during class time.

### Eating and drinking

Eating and drinking are allowed in class, provided it is not disruptive to
others. Please be considerate and clean up after yourself.

### Communication guidelines

- **Respectful communication.** All class discussions and debates must be
  civil, considerate, and free of hate speech and discriminatory language.
  Avoid terms and phrases that can be exclusionary or derogatory. Use
  gender-neutral terms and respect others' gender identities and pronouns.
- **Respect different viewpoints.** Respectful debate and disagreement are
  encouraged, but personal attacks and dismissive comments are not tolerated.
- **Active listening.** Practice active listening during discussions, showing
  respect for others by not interrupting and considering their perspective
  fully before responding.
- **Confidentiality.** Respect the confidentiality of personal information
  shared by classmates during discussions.
- **Professionalism.** Maintain professionalism in communications with the
  instructor and fellow classmates, including emails.
